---
title: "Crinier_2020_Human_BM_NK_preprocessing"
author: "Dillon Corvino"
date: "11/08/2021"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

Built with R version `r getRversion()`

## Setup {.tabset}

### Dataset information
```{r Dataset_Info}




```

### Environment
```{r setup}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)


# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory

# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Load packages
source("R/Load_packages.R", local = knitr::knit_global())

# Create output directories & load custom functions & colour scheme
source("R/Setup.R", local = knitr::knit_global())

long.compute <- FALSE
quick.load <- TRUE

```

### Read and format dataset
```{r reading_data_mouse}

# List files 
data.list <- list.files("Data/GSE159624_RAW/", pattern = ".csv")


############################
# Read in sample data
############################

# Create name variable
file.names <- gsub("_normalized.csv", "", data.list)
file.names <- gsub("GSM([0-9]+)_", "", file.names)
file.names




# Read in samples
for (i in seq_along(data.list)){
  assign(file.names[i], read.csv(paste0("Data/GSE159624_RAW/", data.list[i])))
}

##################
# Read in metadata
##################

# Create name variable
file.names <- gsub(".csv", "", metadata.list)

# Read in metadat
for (i in seq_along(metadata.list)){
  assign(file.names[i], read.csv(paste0("Data/Mouse/Mouse_Meta_data/", metadata.list[i])))
}


# Filter sample data by cell IDs retained in metadata
# Cells retained in metadata are after filtering reported in original paper 

sample1m <- clean.data(sample1m, Mouse1Spleen_metadata)
sample2m <- clean.data(sample2m, Mouse2Spleen_metadata)
sample3m <- clean.data(sample3m, Mouse3Spleen_metadata)

sample4m <- clean.data(sample4m, Mouse1Blood_metadata)
sample5m <- clean.data(sample5m, Mouse2Blood_metadata)
sample6m <- clean.data(sample6m, Mouse3Blood_metadata)


# Annotate the cell ids so can be identified later
colnames(sample1m) <- paste0(colnames(sample1m), "_Sp1")
colnames(sample2m) <- paste0(colnames(sample2m), "_Sp2")
colnames(sample3m) <- paste0(colnames(sample3m), "_Sp3")

colnames(sample4m) <- paste0(colnames(sample4m), "_Bl1")
colnames(sample5m) <- paste0(colnames(sample5m), "_Bl2")
colnames(sample6m) <- paste0(colnames(sample6m), "_Bl3")


########################################
# Merge data by organ of origin
########################################

# Dplyr doesnt allow merge by rowname. so have to make it a variable and then return the variable

# Spleen dataset
sample1m$GeneID <- row.names(sample1m)
sample2m$GeneID <- row.names(sample2m)
sample3m$GeneID <- row.names(sample3m)

spleen.raw <- 
  full_join(sample1m, sample2m,  by = "GeneID") %>%
  full_join(sample3m,  by = "GeneID") %>%
  arrange(desc = TRUE) %>%
  column_to_rownames(var = "GeneID")

# Blood dataset
sample4m$GeneID <- row.names(sample4m)
sample5m$GeneID <- row.names(sample5m)
sample6m$GeneID <- row.names(sample6m)

blood.raw <- 
  full_join(sample4m, sample5m,  by = "GeneID") %>%
  full_join(sample6m,  by = "GeneID") %>%
  arrange(desc = TRUE) %>%
  column_to_rownames(var = "GeneID")


# Checking all genes were merged 
spleen.geneIDs <- unique(c(as.character(sample1m$GeneID), 
                           as.character(sample2m$GeneID), 
                           as.character(sample3m$GeneID)))

length(spleen.geneIDs) == nrow(spleen.raw)

blood.geneIDs <- unique(c(as.character(sample4m$GeneID), 
                          as.character(sample5m$GeneID), 
                          as.character(sample6m$GeneID)))

length(blood.geneIDs) == nrow(blood.raw)

# overview stats
dim(spleen.raw)
dim(blood.raw)

#####################
# Format dataframe
#####################

# Merge all data together
mouse.data <- merge(spleen.raw, blood.raw, 
                    by = "row.names", 
                    all = TRUE)

# Annotate
rownames(mouse.data) <- mouse.data$Row.names

index.val <- grep("^Row.names$", colnames(mouse.data))
colnames(mouse.data)[index.val]
mouse.data <- mouse.data[,-index.val]


# Correct number of columns 
total.geneIDs <- unique(c(spleen.geneIDs, 
                          blood.geneIDs))

length(total.geneIDs) == nrow(mouse.data)

# When a gene was detected in spleen or blood but not the other there are now NA values for this entry in the other dataset cells
# Remove NA values
na.values <- is.na(mouse.data)
sum(na.values) # 10,661,721

# Assigning NA values as 0
mouse.data[na.values] <- 0

# Checking NA values are removed
sum(is.na(mouse.data)) 

dim(mouse.data) # 12,150 genes and 8,193 cells 

# Write data to file for easy use later
write.csv(mouse.data, "output/tables/Mouse_Sp_and_Bl_samples_raw.csv")
saveRDS(mouse.data, "Exported_RDS_files/Mouse_Sp_and_Bl_samples_raw.RDS")
saveRDS(spleen.raw, "Exported_RDS_files/Mouse_Sp_samples_raw.RDS")
saveRDS(blood.raw, "Exported_RDS_files/Mouse_Bl_samples_raw.RDS")

#########################
# Merge metadata
#########################

# Annotate the cell ids so can be identified later

rownames(Mouse1Spleen_metadata) <- paste0(Mouse1Spleen_metadata$X, "_Sp1")
rownames(Mouse2Spleen_metadata) <- paste0(Mouse2Spleen_metadata$X, "_Sp2")
rownames(Mouse3Spleen_metadata) <- paste0(Mouse3Spleen_metadata$X, "_Sp3")

rownames(Mouse1Blood_metadata) <- paste0(Mouse1Blood_metadata$X, "_Bl1")
rownames(Mouse2Blood_metadata) <- paste0(Mouse2Blood_metadata$X, "_Bl2")
rownames(Mouse3Blood_metadata)<- paste0(Mouse3Blood_metadata$X, "_Bl3")


# Mouse_3_spleen used a res = 0.5 whereas everythingelse, clusters were calculated on res = 0.7. 
# remove this and other un-needed variables 

colnames(Mouse1Spleen_metadata)

Mouse1Spleen_metadata <- Mouse1Spleen_metadata[, -c(1, 4, 6)]
Mouse2Spleen_metadata <- Mouse2Spleen_metadata[, -c(1, 4, 6)]
Mouse3Spleen_metadata <- Mouse3Spleen_metadata[, -c(1, 4, 6)]

Mouse1Blood_metadata <- Mouse1Blood_metadata[, -c(1, 4, 6)]
Mouse2Blood_metadata <- Mouse2Blood_metadata[, -c(1, 4, 6)]
Mouse3Blood_metadata <- Mouse3Blood_metadata[, -c(1, 4, 6)]


mouse.metadata <- rbind(Mouse1Spleen_metadata, Mouse2Spleen_metadata, Mouse3Spleen_metadata, 
                        Mouse1Blood_metadata, Mouse2Blood_metadata, Mouse3Blood_metadata)

head(Mouse.metadata)


# Write data to file for easy use later
write.csv(mouse.metadata, "output/tables/Mouse_Sp_and_Bl_metadata.csv")
saveRDS(mouse.metadata, "Exported_RDS_files/Mouse_Sp_and_Bl_metadata.RDS")


# remove large datafiles
rm(sample1m, sample2m, sample3m, 
   sample4m, sample5m, sample6m, 
   spleen.raw, mouse.data, blood.raw, 
   mouse.metadata, Mouse1Spleen_metadata, Mouse2Spleen_metadata, Mouse3Spleen_metadata, 
   Mouse1Blood_metadata, Mouse2Blood_metadata, Mouse3Blood_metadata)

```

# Create seurat object
```{r create_Seurat_object}

mouse.data <- readRDS("Exported_RDS_files/Mouse_Sp_and_Bl_samples_raw.RDS")
mouse.metadata <- readRDS("Exported_RDS_files/Mouse_Sp_and_Bl_metadata.RDS")

dim(mouse.data)
mouse.data[1:10, 1:10]


# Initialize the Seurat object with the raw (non-normalized data).  
# Keep all genes expressed in >= 3 cells. 
# Keep all cells with at least 200 detected genes

mouse.seurat <- CreateSeuratObject(counts = mouse.data,
                                   meta.data = mouse.metadata, 
                                   min.cells = 3, 
                                   min.genes = 200,
                                   is.expr = 0, # for UMI datasets this should be 0, and is default
                                   project = "Mouse_NK",
                                   display.progress = TRUE)



# Create metadata
donor.ID <- gsub(".*_", "", rownames(mouse.seurat@meta.data))
organ <- gsub("[[:digit:]]", "", donor.ID)
organ <- gsub("Sp", "Spleen", organ)
organ <- gsub("Bl", "Blood", organ)
unique(organ)


mouse.seurat@meta.data$donor <- donor.ID
mouse.seurat@meta.data$organ <- organ

saveRDS(mouse.seurat, "Exported_RDS_files/Mouse_raw_Seurat_Object.RData")

```


## QC and Norm {.tabset}
### QC
```{r QC}

################################################
#  Get percentage Mitochondria gene expression
################################################

species.ori <- "mouse"

if (species.ori == "mouse") {
  pat <- "^mt-"
}else if (species.ori == "human"){
  pat <- "^MT-"
}


mouse.seurat[["percent.mito.recalc"]] <- PercentageFeatureSet(mouse.seurat, pattern = paste0(pat))


VlnPlot(mouse.seurat, 
        features = c("nFeature_RNA", "nCount_RNA"),
        pt.size = 0.1)

dev.copy(pdf, "output/QC/QC_nFeature_nCount_RNA_percentMito.pdf")
dev.off()


VlnPlot(mouse.seurat, 
        features = c("percent.mito", "percent.mito.recalc"), 
        pt.size = 0.1)


dev.copy(pdf, "output/QC/QC_percentMito.pdf")
dev.off()


#  Filter cells
# Remove cells with < 200 genes, and remove cells with > 10% mitochondrial genes
mouse.seurat.filt <- subset(mouse.seurat, 
                            subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mito.recalc < 10)


# Vis after filtering

p1 <- VlnPlot(mouse.seurat, 
              features = "percent.mito.recalc", 
              pt.size = 0.1, 
              y.max = 20) + NoLegend() + 
  ggtitle("Before filtering")

p2 <- VlnPlot(mouse.seurat.filt, 
              features = "percent.mito.recalc", 
              pt.size = 0.1, 
              y.max = 20) + NoLegend() + 
  ggtitle("After filtering")

p1 | p2

dev.copy(pdf, "output/QC/QC_percentMito_filtering.pdf")
dev.off()


p1 <- VlnPlot(mouse.seurat, 
              features = "nFeature_RNA", 
              pt.size = 0.1, 
              y.max = 2500) + NoLegend() + 
  ggtitle("Before filtering")

p2 <- VlnPlot(mouse.seurat.filt, 
              features = "nFeature_RNA", 
              pt.size = 0.1, 
              y.max = 2500) + NoLegend() + 
  ggtitle("After filtering")

p1 | p2

dev.copy(pdf, "output/QC/QC_nFeature_RNA_filtering.pdf")
dev.off()


# Stats
mouse.seurat # 12,121 genes across 8,193 cells
mouse.seurat.filt # 12,121 genes across 8,180 cells

# Therefore
8193 - 8180
# 13 cells were deleted


####################################
# Annotating data by organ origin
####################################

#  Add organ label to metadata
organ <- rownames(mouse.seurat.filt@meta.data)
organ <- gsub(".*_","", organ)
organ <- gsub("Sp","Spleen", organ)
organ <- gsub("Bl","Blood", organ)
organ <- gsub("[[:digit:]]","", organ)
mouse.seurat.filt@meta.data$organ <- organ


# QC plots subset by organ assignment
VlnPlot(mouse.seurat.filt, 
        features = c("nFeature_RNA"), 
        group.by = "organ",
        pt.size = 0.1)

dev.copy(pdf, "output/QC/QC_nFeature_postfiltering_byorgan.pdf")
dev.off()


# QC plots subset by organ assignment
VlnPlot(mouse.seurat.filt, 
        features = c("nCount_RNA"), 
        group.by = "organ",
        pt.size = 0.1)

dev.copy(pdf, "output/QC/QC_nCount_postfiltering_byorgan.pdf")
dev.off()


# QC plots subset by organ assignment
VlnPlot(mouse.seurat.filt, 
        features = c("percent.mito.recalc"), 
        group.by = "organ",
        pt.size = 0.1)

dev.copy(pdf, "output/QC/QC_percentMito_postfiltering_byorgan.pdf")
dev.off()



```


### Filtering dataset and subsetting dataset 
```{r filtering_and_subsetting_dataset}

##################
# Filter dataset 
##################

# Remove cells with no crinier cluster annotation
keep.logic <- mouse.seurat.filt@meta.data$cluster != "none"
cells.keep <- rownames(mouse.seurat.filt@meta.data)[keep.logic]

mouse.seurat.filt <- subset(mouse.seurat.filt, cells = cells.keep)



# Split dataset by organ
Idents(mouse.seurat.filt) <- mouse.seurat.filt@meta.data$organ


spleen.seurat.filt <- subset(mouse.seurat.filt, idents = "Spleen")
blood.seurat.filt <- subset(mouse.seurat.filt, idents = "Blood")


```



### Normalise datasets 
```{r normalise_datasets}

################################################
# Normalise, scale & find variable genes 
################################################


datasets.list <- list(mouse.seurat.filt, spleen.seurat.filt,  blood.seurat.filt)
names(datasets.list)  <- c("Complete", "Spleen", "Blood")

for(i in seq_along(datasets.list)){
  
  # Normalise RNA data by logNormalize
  datasets.list[[i]] <- NormalizeData(datasets.list[[i]],
                                      normalization.method = "LogNormalize",
                                      scale.factor = 10000,
                                      verbose = TRUE)
  
  
  # Find variable genes
  datasets.list[[i]] <- FindVariableFeatures(datasets.list[[i]],
                                             nfeatures = 1000,
                                             verbose = TRUE)
  
  # Scale data
  datasets.list[[i]] <- ScaleData(datasets.list[[i]],
                                  vars.to.regress = c("nCount_RNA", "percent.mito.recalc"),
                                  model.use = "linear",
                                  do.scale = TRUE,
                                  do.center = TRUE,
                                  verbose = TRUE)
  
  
}


# Remove unneeded variables
rm(mouse.seurat)

```



## Unbiased Clustering {.tabset}

### Clustering
```{r Initial_clustering}

# Set seed for reproducibility
set.seed(42)


#################################################################
# Determine statistically significant principal components
#################################################################

# Use quick approximation of significant PCs
#ElbowPlot(mouse.seurat.filt, ndims = 30)
#dev.copy(pdf, "output/QC/PC_elbowplot.pdf")
#dev.off()



# NOTE: This process can take a long time for big datasets, comment out for
# expediency.  More approximate techniques such as those implemented in
# PCElbowPlot() can be used to reduce computation time

if(long.compute){
  
  mouse.seurat.filt <- JackStraw(mouse.seurat.filt,
                                 dims = 50)
  mouse.seurat.filt <- ScoreJackStraw(mouse.seurat.filt,
                                      dims = 1:50)
  
  JackStrawPlot(mouse.seurat.filt, dims = 1:30)
  
  dev.copy(pdf, "output/QC/JackStrawPlot.pdf")
  dev.off()
  
}

# PC 21 = last sig dim
# therefore use 20 dims


###################################
# PCA and cluster identification
###################################


for(i in seq_along(datasets.list)){
  
  # Create output dir
  output.path <- paste0("output/figures/PCA_", names(datasets.list)[i])
  
  
  if(!dir.exists(output.path)){
    dir.create(output.path, 
               recursive = TRUE)}
  
  # Run PCA
  datasets.list[[i]] <- RunPCA(datasets.list[[i]], 
                               features = datasets.list[[i]]@assays$RNA@var.features,
                               npcs = 20,
                               verbose = TRUE, 
                               rev.pca = TRUE,
                               seed.use = 42)
  
  # Plot PCA projection
  print(PCAPlot(datasets.list[[i]], 
          dims = c(1, 2),
          pt.size = 2,
          group.by = "organ"))
  
  dev.copy(pdf, paste0(output.path, "/PCA_by_organ_Dim1_2.pdf"))
  dev.off()
  
  print(PCAPlot(datasets.list[[i]], 
          dims = c(2, 3),
          pt.size = 2,
          group.by = "organ"))
  
  dev.copy(pdf, paste0(output.path, "/PCA_by_organ_Dim2_3.pdf"))
  dev.off()
  
  
  
  # Find neighbours
  datasets.list[[i]] <- FindNeighbors(datasets.list[[i]],
                                      dims = 1:20)
  
  # Find clusters
  datasets.list[[i]] <- FindClusters(datasets.list[[i]],
                                     resolution = 0.1)
  
}


```


### UMAP and tSNE dim Reduction
```{r Dim_reduction}



for(i in seq_along(datasets.list)){
  
  # Set assay 
  DefaultAssay(datasets.list[[i]]) <- "RNA"
  
  # Set Idents
  Idents(datasets.list[[i]]) <- datasets.list[[i]]@meta.data$organ
  
  
  
  
  ##########
  # TSNE
  ##########
  
  # Create output dir
  output.path <- paste0("output/figures/tSNE_", names(datasets.list)[i])
  
  
  if(!dir.exists(output.path)){
    dir.create(output.path, 
               recursive = TRUE)}
  
  
  
  
  datasets.list[[i]] <- RunTSNE(datasets.list[[i]],
                                reduction = "pca",
                                dims = 1:20,
                                perplexity = 30,
                                method = "FIt-SNE",
                                seed.use = 42,
                                dim.embed = 2)
  
  print(TSNEPlot(datasets.list[[i]],
           label = TRUE, 
           group.by = "organ"))
  
  dev.copy(pdf,  paste0(output.path, "/tSNE_by_organ.pdf"))
  dev.off()
  
  
  
  print(TSNEPlot(datasets.list[[i]],
           label = TRUE, 
           group.by = "seurat_clusters"))
  
  dev.copy(pdf, paste0(output.path, "/tSNE_by_seurat_clusters.pdf"))
  dev.off()
  
  
  # using original author clusters
  print(TSNEPlot(datasets.list[[i]],
           label = TRUE, 
           group.by = "cluster"))
  
  dev.copy(pdf, paste0(output.path, "/tSNE_by_crinier_clusters.pdf"))
  dev.off()
  
    print(TSNEPlot(datasets.list[[i]],
           label = TRUE, 
           group.by = "donor"))
  
  dev.copy(pdf, paste0(output.path, "/tSNE_by_donor.pdf"))
  dev.off()
  
  ##########
  # UMAP
  ##########
  
  # Create output dir
  output.path <- paste0("output/figures/UMAP_", names(datasets.list)[i])
  
  
  if(!dir.exists(output.path)){
    dir.create(output.path, 
               recursive = TRUE)}
  
  
  datasets.list[[i]] <- RunUMAP(datasets.list[[i]],
                                reduction = "pca",
                                dims = 1:20,
                                umap.method = "uwot", 
                                n.neighbors = 45, # 5 to 50 // 45
                                min.dist = 0.5, # Sensible values are in the range 0.001 to 0.5 // 0.5
                                seed.use = 42)
  
  # Larger values = global structure
  # small value = local structure
  
  print(UMAPPlot(datasets.list[[i]],
           label = T,
           group.by = "organ"))
  
  dev.copy(pdf, paste0(output.path, "/UMAP_by_organ.pdf"))
  dev.off()
  
  print(UMAPPlot(datasets.list[[i]],
           label = TRUE, 
           group.by = "seurat_clusters"))
  
  dev.copy(pdf, paste0(output.path, "/UMAP_by_seurat_clusters.pdf"))
  dev.off()
  
  # Original Author clusters
  print(UMAPPlot(datasets.list[[i]],
           label = TRUE, 
           group.by = "cluster"))
  
  dev.copy(pdf, paste0(output.path, "/UMAP_by_crinier_clusters.pdf"))
  dev.off()
  
  print(UMAPPlot(datasets.list[[i]],
           label = TRUE, 
           group.by = "donor"))
  
  dev.copy(pdf, paste0(output.path, "/UMAP_by_donor.pdf"))
  dev.off()
  
}


```


### Export seurat objects
```{r export_seurat_RDS}

for(i in seq_along(datasets.list)){

saveRDS(datasets.list[[i]], file = paste0("Exported_RDS_files/Mouse_", names(datasets.list)[i], "_seurat_filt.rds"))

  
}


```



## Imputation {.tabset}

### Imputation calculation
```{r seurat_imputation}


for(i in seq_along(datasets.list)){

# Impute gene expression 
datasets.list[[i]] <- RunALRA(datasets.list[[i]], 
                             genes.use = rownames(datasets.list[[i]]))

#The matrix went from 7.41% nonzero to 61.04% nonzero

# set assay 
DefaultAssay(datasets.list[[i]]) <- "RNA"

saveRDS(datasets.list[[i]], file = paste0("Exported_RDS_files/Mouse_", names(datasets.list)[i], "_seurat_filt_imputed.rds"))


}


```


